FizzBuzzBazaDanych/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FizzBuzzBazaDanych.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FizzBuzzBazaDanych.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly FizzBuzzBazaDanych.Data.FizzBuzzContext _context;

        public DeleteModel(FizzBuzzBazaDanych.Data.FizzBuzzContext context)
        {
            _context = context;
        }

        [BindProperty]
        public FizzBuzz FizzBuzz { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FizzBuzz = await _context.FizzBuzzData.FirstOrDefaultAsync(m => m.Id == id);

            if (FizzBuzz == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FizzBuzz = await _context.FizzBuzzData.FindAsync(id);

            if (FizzBuzz != null)
            {
                _context.FizzBuzzData.Remove(FizzBuzz);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

FizzBuzzBazaDanych/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FizzBuzzBazaDanych.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

FizzBuzzBazaDanych/Pages/Index.cshtml.cs
using FizzBuzzBazaDanych.Data;
using FizzBuzzBazaDanych.Forms;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FizzBuzzBazaDanych.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly FizzBuzzContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        [Display(Name = "Podaj Wartość: "), BindProperty]
        [Range(1, 1000, ErrorMessage = "Wartość musi być z przedziału {1}-{2}"), Required(ErrorMessage = "To pole jest wymagane")]
        public int InputValue { get; set; }
        public FizzBuzz CurrentFizzBuzz { get; set; }

        public IndexModel(ILogger<IndexModel> logger, FizzBuzzContext context, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                CurrentFizzBuzz = new FizzBuzz();
                string userId = _userManager.GetUserId(User);
                CurrentFizzBuzz.Calculate(InputValue, userId);
                HttpContext.Session.SetString("SessionFizzBuzz", JsonConvert.SerializeObject(CurrentFizzBuzz));
                _context.FizzBuzzData.Add(CurrentFizzBuzz);
                _context.SaveChangesAsync();
                return Page();
            }
            return Page();
        }
    }
}

FizzBuzzBazaDanych/Pages/LastSearched.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using FizzBuzzBazaDanych.Forms;
using Newtonsoft.Json;

namespace FizzBuzzBazaDanych.Pages
{
    public class LastSearchedModel : PageModel
    {
        public FizzBuzz CurrentFizzBuzz { get; set; }
        public void OnGet()
        {
            var SessionInputValue = HttpContext.Session.GetString("SessionFizzBuzz");
            if (SessionInputValue != null)
                CurrentFizzBuzz = JsonConvert.DeserializeObject<FizzBuzz>(SessionInputValue);
        }

    }
}

FizzBuzzBazaDanych/Pages/LastSearchedDatabase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FizzBuzzBazaDanych.Data;
using FizzBuzzBazaDanych.Forms;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FizzBuzzBazaDanych.Pages
{
    [Authorize]
    public class LastSearchedDatabaseModel : PageModel
    {
        private readonly FizzBuzzContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public IList<FizzBuzz> FizzBuzzEntries { get; set; }
        public LastSearchedDatabaseModel(FizzBuzzContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public void OnGet()
        {
            var FizzBuzzQuery = (from FizzBuzzData in _context.FizzBuzzData
                                orderby FizzBuzzData.LastSearchDate descending
                                select FizzBuzzData).Take(20);
            FizzBuzzEntries = FizzBuzzQuery.ToList();
        }
        public void OnGetUserList()
        {
            string userId = _userManager.GetUserId(User);
            var FizzBuzzQuery = (from FizzBuzzData in _context.FizzBuzzData
                                 where FizzBuzzData.Creator == userId
                                 orderby FizzBuzzData.LastSearchDate descending
                                 select FizzBuzzData).Take(20);
            FizzBuzzEntries = FizzBuzzQuery.ToList();
        }
    }
}

FizzBuzzBazaDanych/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FizzBuzzBazaDanych.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

FizzBuzzBazaDanych/Pages/Delete.cshtml
@page
@model FizzBuzzBazaDanych.Pages.DeleteModel
@{
}

@inject UserManager<IdentityUser> UserManager
@using Microsoft.AspNetCore.Identity

<h3>Czy na pewno chcesz usunąć ten wpis?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FizzBuzz.Result)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FizzBuzz.Result)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FizzBuzz.SearchedValue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FizzBuzz.SearchedValue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FizzBuzz.LastSearchDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FizzBuzz.LastSearchDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FizzBuzz.Creator)
        </dt>
        @if (Model.FizzBuzz.Creator == UserManager.GetUserId(User))
        {
            <dt class="col-sm-2">
                <h6>Ten wpis został dodany przez ciebie</h6>
            </dt>
        }
        else
        {
            <dd class="col-sm-10">
                <p class="text-secondary">Ten wpis został dodany przez innego użytkownia. Oznacza to, że nie możesz go usunąć</p>
            </dd>
        }
    </dl>
    @if (Model.FizzBuzz.Creator == UserManager.GetUserId(User))
    {
        <form method="post">
            <input type="hidden" asp-for="FizzBuzz.Id" />
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            <a asp-page="./Index">Wróć do strony głównej</a>
        </form>
    }
</div>

FizzBuzzBazaDanych/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h2 class="display-4"> Welcome to FizzBuzz <b>Web Edition</b></h2><br />
    <form method="post">
        <label asp-for="InputValue"></label>
        <span asp-validation-for="InputValue" class="text-danger"></span>
        <input asp-for="InputValue" /><br /><br />
        <button class="btn btn-primary" type="submit">Zatwierdź</button>
    </form><br />
    @if (Model.CurrentFizzBuzz != null)
    {
        @if (Model.CurrentFizzBuzz.Result == "")
        {
            <h3>
                Liczba: @Model.CurrentFizzBuzz.SearchedValue nie spełnia kryteriów Fizz/Buzz
            </h3>
        }
        else
        {
            <h3>
                Otrzymano: @Model.CurrentFizzBuzz.Result
            </h3>
        }
    }

</div>

FizzBuzzBazaDanych/Pages/LastSearched.cshtml
@page
@model FizzBuzzBazaDanych.Pages.LastSearchedModel
@{
}
<p>Dane zapisane z ostatniego wyszukania FizzBuzz</p>
@if (Model.CurrentFizzBuzz != null)
{
    <p>
        @Html.DisplayNameFor(model => Model.CurrentFizzBuzz.Result):
        @Model.CurrentFizzBuzz.Result
    </p>
    <p>
        @Html.DisplayNameFor(model => Model.CurrentFizzBuzz.SearchedValue):
        @Model.CurrentFizzBuzz.SearchedValue
    </p>
    <p>
        @Html.DisplayNameFor(model => Model.CurrentFizzBuzz.LastSearchDate):
        @Model.CurrentFizzBuzz.LastSearchDate
    </p>
}

FizzBuzzBazaDanych/Pages/LastSearchedDatabase.cshtml
@page
@model FizzBuzzBazaDanych.Pages.LastSearchedDatabaseModel
@{
}
<p>Dane zapisane z ostatnich wyszukiwań FizzBuzz</p>
<div class="btn-group-vertical float-right">
    <a class="btn btn-secondary float-right mb-2" asp-page-handler="OnGet" asp-page="./LastSearchedDatabase">wyświetl wszystkie wpisy</a>
    <a class="btn btn-info float-right" asp-page-handler="UserList" asp-page="./LastSearchedDatabase">wyświetl tylko moje wpisy</a>
</div>
<div>
    @foreach (var item in Model.FizzBuzzEntries)
    {
        <h3>
            @Html.DisplayNameFor(model => item.Id):
            @item.Id
        </h3>
        <p>
            @Html.DisplayNameFor(model => item.Result):
            @item.Result
        </p>
        <p>
            @Html.DisplayNameFor(model => item.SearchedValue):
            @item.SearchedValue
        </p>
        <p>
            @Html.DisplayNameFor(model => item.LastSearchDate):
            @item.LastSearchDate
            <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
        </p>
    }
</div>